// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import BirdController from "./bird_controller"
import CheckBoxController from "./checkbox_controller"
import EditController from "./edit_controller"
import FiltersController from "./filters_controller"
import LookController from "./look_controller"
import PopulateController from "./populate_controller"
import QuestionController from "./question_controller"
import ReplyController from "./reply_controller"
import TurboFrameHistoryController from "./turbo_frame_history_controller"
import UserController from "./user_controller"
import AnimationController from "./animation_controller"
import ModalController from "./modal_controller"
import HiderController from "./hider_controller"


application.register("bird", BirdController)
application.register("checkbox", CheckBoxController)
application.register("edit", EditController)
application.register("filters", FiltersController)
application.register("look", LookController)
application.register("populate", PopulateController)
application.register("question", QuestionController)
application.register("reply", ReplyController)
application.register("turbo-frame-history", TurboFrameHistoryController)
application.register("user", UserController)
application.register("animation", AnimationController)
application.register("modal", ModalController)
application.register("hider", HiderController)
